# Generated by Django 4.2.7 on 2023-11-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contactos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("correo", models.CharField(max_length=100)),
                ("telefono", models.IntegerField()),
                ("mensaje", models.TextField()),
                ("condiciones", models.BooleanField(default=False)),
            ],
        ),
    ]
