# Generated by Django 4.2.7 on 2023-11-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="condiciones",
        ),
        migrations.AddField(
            model_name="user",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]
